[project]
name = "cs336_basics"
version = "1.0.3"
description = "CS336 Assignment 1"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "annotated-types==0.7.0",
    "asttokens==3.0.0",
    "certifi==2025.1.31",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "cloudpickle==3.1.1",
    "colorama==0.4.6",
    "comm==0.2.2",
    "cs336-basics==1.0.3",
    "debugpy==1.8.14",
    "decorator==5.2.1",
    "docker-pycreds==0.4.0",
    "einops==0.8.1",
    "einx==0.3.0",
    "executing==2.2.0",
    "filelock==3.18.0",
    "frozendict==2.4.6",
    "fsspec==2025.3.2",
    "gitdb==4.0.12",
    "gitpython==3.1.44",
    "idna==3.10",
    "iniconfig==2.1.0",
    "ipykernel==6.29.5",
    "ipython==9.2.0",
    "ipython-pygments-lexers==1.1.1",
    "jaxtyping==0.3.1",
    "jedi==0.19.2",
    "jinja2==3.1.6",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "markupsafe==3.0.2",
    "matplotlib-inline==0.1.7",
    "mpmath==1.3.0",
    "nest-asyncio==1.6.0",
    "networkx==3.4.2",
    "numpy==2.2.4",
    "packaging==24.2",
    "parso==0.8.4",
    "pillow==11.0.0",
    "pip==24.2",
    "platformdirs==4.3.7",
    "pluggy==1.5.0",
    "prompt-toolkit==3.0.51",
    "protobuf==5.29.4",
    "psutil==7.0.0",
    "pure-eval==0.2.3",
    "pydantic==2.11.3",
    "pydantic-core==2.33.1",
    "pygments==2.19.1",
    "pytest==8.3.5",
    "python-dateutil==2.9.0.post0",
    "pywin32==310",
    "pyyaml==6.0.2",
    "pyzmq==26.4.0",
    "regex==2024.11.6",
    "requests==2.32.3",
    "sentry-sdk==2.25.1",
    "setproctitle==1.3.5",
    "setuptools==78.1.0",
    "six==1.17.0",
    "smmap==5.0.2",
    "stack-data==0.6.3",
    "submitit==1.5.2",
    "sympy==1.13.1",
    "tiktoken==0.9.0",
    #"torch>=2.2.1",
    #"torchaudio>=2.7.1", 
    #"torchvision>=0.22.1",
    #"torch==2.7.1+cu118; sys_platform != 'darwin' or platform_machine != 'x86_64'",
    #"torchaudio==2.7.1+cu118; sys_platform != 'darwin' or platform_machine != 'x86_64'",
    #"torchvision==0.22.1+cu118; sys_platform != 'darwin' or platform_machine != 'x86_64'",
    "torch~=2.6.0; sys_platform != 'darwin' or platform_machine != 'x86_64'",
    "torch~=2.2.2; sys_platform == 'darwin' and platform_machine == 'x86_64'", # Intel Macs
    "tornado==6.4.2",
    "tqdm==4.67.1",
    "traitlets==5.14.3",
    "typing-extensions==4.13.1",
    "typing-inspection==0.4.0",
    "urllib3==2.3.0",
    "wadler-lindig==0.1.4",
    "wandb==0.19.9",
    "wcwidth==0.2.13",
]

[tool.setuptools.packages.find]
include = ["cs336_basics"]

[tool.uv]
package = true
python-preference = "managed"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "WARNING"
addopts = "-s"

[tool.ruff]
line-length = 120

[tool.ruff.lint.extend-per-file-ignores]
# Also ignore `E402` in all `__init__.py` files.
"__init__.py" = ["E402", "F401", "F403", "E501"]

[tool.ruff.lint]
extend-select = ["UP"]
ignore = [
    "F722"
]
